### ISSUE TITLE
Questions about "train on the temporal and spatial streams independently"

### ISSUE THREAD

**Issue by XiongChengxin** [mvcnn/mvcnn#5]
Dear author,
    Thanks for your work.
    I have two questions.
    First, in the part of Network Training, you said "We train on the temporal and spatial streams independently", I am confused about this. Does this means it would generate two kinds of models (one  for temporal streams, the other for spatial streams)? 
    Second, in the command "python convert_UCF_bin.py --data_dir=<path to motion vector data dir (ucf_8x8_w10_r1_bin)> --out_dir=<path to output dir> --path_to_file_list=<path to train split 1 file list (ucfTrainTestlist/trainlist01.txt)>", how to generate "ucf_8x8_w10_r1_bin"? What is the relation between "ucf_8x8_w10_r1_bin" and "out.mv" generated by "./mvx -w 1 -r 10 -t 0 --rgb out.rgb --mv out.mv gbr_sample.mp4"?
  Looking forward to your reply.

**Comment by git-alhabib** [comment]
Hello Xiong,
Thanks for your questions, to clarify on both questions:

1 - Does this means it would generate two kinds of models (one for temporal streams, the other for spatial streams)?

Answer: The training code we give is to reproduce the results of the temporal stream only (the novelty of our work is relevant to the temporal stream only). Once you have trained the temporal stream, you can fuse or average its predictions with any available VGG-16 network trained for the UCF101, for example, the one here: http://www.robots.ox.ac.uk/~vgg/software/two_stream_action/

2 -  how to generate "ucf_8x8_w10_r1_bin"? What is the relation between "ucf_8x8_w10_r1_bin" and "out.mv" generated by "./mvx -w 1 -r 10 -t 0 --rgb out.rgb --mv out.mv gbr_sample.mp4"?

Answer: "ucf_8x8_w10_r1_bin" is just an example name for where the spatial data is located. You can use our MVX tool to output selectively decoded spatial data by specifying the "--rgb" flag for a video. So in your example syntax, "ucf_8x8_w10_r1_bin" is the directory where the output of "--rgb" for all videos should be located.

**Comment by XiongChengxin** [comment]
I got it, thanks for your reply.
